version: '3.6'

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    restart: unless-stopped
    volumes:
      - ${ROOT_DIR}:/media
      - ./fb-data:/data
      - ./fb-config:/config
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Madrid
    ports:
      - 8082:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.${HTTP_HOST}`)"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=lets-encrypt"
      - "traefik.port=8080"
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
